use super::ToolVisibility::ModelVisible;
use super::{
    def, model_spec, permission_risk, require_all_scopes, ToolDefinition, PERMISSION_RISK_WRITE,
    TOOL_CATEGORY_COMMUNICATION,
};
use crate::audit_policy::*;
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{CommunicationManage, Read},
    COMMUNICATION_MANAGE, COMMUNICATION_READ, TOOL_PROVIDER_CONTROL,
};
use crate::registry::input_schemas::{
    attach_agent_endpoint_input_schema, bootstrap_agent_conversation_input_schema,
    consume_agent_deliveries_input_schema, consume_agent_wake_input_schema,
    create_agent_identity_input_schema, create_conversation_input_schema,
    detach_agent_endpoint_input_schema, list_agent_identities_input_schema,
    list_agent_inbox_input_schema, list_conversations_input_schema,
    post_conversation_message_input_schema, read_conversation_input_schema,
    update_agent_identity_input_schema,
};
use webcodex_core::authority::{COMMUNICATION_MANAGE_SCOPES, COMMUNICATION_READ_SCOPES};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        model_spec(
            def(
                "create_agent_identity",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("handle_chars", "handle", AuditValue::Chars),
                            AuditField::new("display_name_chars", "display_name", AuditValue::Chars),
                            AuditField::new("description_bytes", "description", AuditValue::Bytes),
                            AuditField::new(
                                "specialty_label_count",
                                "specialty_labels",
                                AuditValue::Count,
                            ),
                            AuditField::new(
                                "idempotency_key_present",
                                "idempotency_key",
                                AuditValue::StringPresent,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("agent_id", "/agent/agent_id", AuditValue::Nullable),
                        AuditField::new(
                            "profile_revision",
                            "/agent/profile_revision",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("created", "created", AuditValue::Nullable),
                        AuditField::new("replayed", "replayed", AuditValue::Nullable),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Create a durable Server-owned Agent identity and mutable self-description card. The canonical wc_dagent_* id is independent from windows, Endpoints, Workflow Sessions, Projects, and execution authority. Exact idempotency-key replay returns the original Agent; changed reuse is rejected.",
            create_agent_identity_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_agent_identities",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("offset", "offset", AuditValue::Copy),
                            AuditField::new("limit", "limit", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("total_count", "total_count", AuditValue::Nullable),
                        AuditField::new("returned_count", "agents", AuditValue::NullableCount),
                        AuditField::new("offset", "offset", AuditValue::Nullable),
                        AuditField::new("next_offset", "next_offset", AuditValue::Nullable),
                        AuditField::new("truncated", "truncated", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "List bounded durable Agent cards owned by the current communication principal, or read one exact Agent. Handles, names, descriptions, labels, and Endpoint counts are metadata only and never grant Project, filesystem, Runner, or Workflow Session authority.",
            list_agent_identities_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "update_agent_identity",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_profile_revision",
                                "expected_profile_revision",
                                AuditValue::Copy,
                            ),
                            AuditField::new("handle_present", "handle", AuditValue::Present),
                            AuditField::new("display_name_present", "display_name", AuditValue::Present),
                            AuditField::new("description_present", "description", AuditValue::Present),
                            AuditField::new(
                                "specialty_labels_present",
                                "specialty_labels",
                                AuditValue::Present,
                            ),
                            AuditField::new("description_bytes", "description", AuditValue::Bytes),
                            AuditField::new(
                                "specialty_label_count",
                                "specialty_labels",
                                AuditValue::Count,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("agent_id", "/agent/agent_id", AuditValue::Nullable),
                        AuditField::new(
                            "profile_revision",
                            "/agent/profile_revision",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("created", "created", AuditValue::Nullable),
                        AuditField::new("replayed", "replayed", AuditValue::Nullable),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Update an owned Agent Card behind expected_profile_revision. Canonical agent_id never changes, and handle/display-name collisions remain allowed. On uncertain outcome, re-read the Agent instead of changing the revision fence blindly.",
            update_agent_identity_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "attach_agent_endpoint",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("host", "host", AuditValue::Copy),
                            AuditField::new(
                                "client_attachment_id_present",
                                "client_attachment_id",
                                AuditValue::Present,
                            ),
                            AuditField::new(
                                "idempotency_key_present",
                                "idempotency_key",
                                AuditValue::StringPresent,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("endpoint_id", "/endpoint/endpoint_id", AuditValue::Nullable),
                        AuditField::new("agent_id", "/endpoint/agent_id", AuditValue::Nullable),
                        AuditField::new("created", "created", AuditValue::Nullable),
                        AuditField::new("replayed", "replayed", AuditValue::Nullable),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                        AuditField::new(
                            "detached",
                            "/endpoint/detached_at_unix_ms",
                            AuditValue::Present,
                        ),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Attach a replacement Host/Client Endpoint to an owned durable Agent. The Server assigns a new monotonic controller generation and fences every older attachment. Public attachment is not wake-capable; only callable process-local Host adapter registration may enable continuation. Exact idempotency replay returns the original Endpoint.",
            attach_agent_endpoint_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "bootstrap_agent_conversation",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new("conversation_id", "conversation_id", AuditValue::Copy),
                            AuditField::new("wake_id", "wake_id", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("agent_id", "/acting_agent/agent_id", AuditValue::Nullable),
                        AuditField::new("endpoint_id", "/endpoint/endpoint_id", AuditValue::Nullable),
                        AuditField::new(
                            "controller_generation",
                            "/endpoint/controller_generation",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "conversation_id",
                            "/selected_conversation/conversation_id",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "queued_delivery_count",
                            "/inbox/queued_delivery_count",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("wake_id", "/wake/wake_id", AuditValue::Nullable),
                        AuditField::new("wake_state", "/wake/state", AuditValue::Nullable),
                        AuditField::new(
                            "adapter_kind",
                            "/host_binding/adapter_kind",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "runtime_wake_capable",
                            "/host_binding/runtime_wake_capable",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "production_auto_resume_available",
                            "/host_binding/production_auto_resume_available",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Verify an exact Agent/Endpoint generation and return bounded turn context without Message bodies. With an activation idempotency key, accept one pending Wake into this already-active explicit turn and return a replayable consume token; this does not request a new model turn.",
            bootstrap_agent_conversation_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "detach_agent_endpoint",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("endpoint_id", "/endpoint/endpoint_id", AuditValue::Nullable),
                        AuditField::new("agent_id", "/endpoint/agent_id", AuditValue::Nullable),
                        AuditField::new("created", "created", AuditValue::Nullable),
                        AuditField::new("replayed", "replayed", AuditValue::Nullable),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                        AuditField::new(
                            "detached",
                            "/endpoint/detached_at_unix_ms",
                            AuditValue::Present,
                        ),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Detach a principal-bound Agent Endpoint without deleting the durable Agent, Conversation transcript, or Inbox. Repeating the same detach is a safe desired-state retry; a new Endpoint may later attach the same agent_id.",
            detach_agent_endpoint_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "create_conversation",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("title_present", "title", AuditValue::Present),
                            AuditField::new("agent_count", "agent_ids", AuditValue::Count),
                            AuditField::new(
                                "idempotency_key_present",
                                "idempotency_key",
                                AuditValue::StringPresent,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new(
                            "conversation_id",
                            "/conversation/conversation/conversation_id",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "participant_count",
                            "/conversation/participants",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new(
                            "message_count",
                            "/conversation/messages",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new("created", "created", AuditValue::Nullable),
                        AuditField::new("replayed", "replayed", AuditValue::Nullable),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Create a durable Conversation containing the current Human principal and one or more owned Agents. Participation authorizes communication only, never Project, filesystem, Runner, Task, or Workflow Session execution. Exact idempotency-key replay returns the original Conversation.",
            create_conversation_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_conversations",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new("offset", "offset", AuditValue::Copy),
                            AuditField::new("limit", "limit", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("total_count", "total_count", AuditValue::Nullable),
                        AuditField::new("returned_count", "conversations", AuditValue::NullableCount),
                        AuditField::new("offset", "offset", AuditValue::Nullable),
                        AuditField::new("next_offset", "next_offset", AuditValue::Nullable),
                        AuditField::new("truncated", "truncated", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "List bounded Conversations visible to the current Human principal, or to an Agent proven by an active principal-bound Endpoint. Agent views include queued-delivery counts; listing never consumes Inbox state or invokes a model.",
            list_conversations_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "read_conversation",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("conversation_id", "conversation_id", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new("after_seq", "after_seq", AuditValue::Copy),
                            AuditField::new("limit", "limit", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new(
                            "conversation_id",
                            "/conversation/conversation_id",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "participant_count",
                            "participants",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new("message_count", "messages", AuditValue::NullableCount),
                        AuditField::new("after_seq", "after_seq", AuditValue::Nullable),
                        AuditField::new("next_after_seq", "next_after_seq", AuditValue::Nullable),
                        AuditField::new("truncated", "truncated", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "Read a bounded ordered page from an append-only durable Conversation transcript, with participant and author provenance. Use after_seq for deterministic continuation. Reading does not consume recipient-specific Inbox deliveries or wake a model.",
            read_conversation_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "post_conversation_message",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("conversation_id", "conversation_id", AuditValue::Copy),
                            AuditField::new("author_agent_id", "author_agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new("reply_to", "reply_to", AuditValue::Copy),
                            AuditField::new("wake_reply_id", "wake_reply_id", AuditValue::Copy),
                            AuditField::new(
                                "reply_operation_index",
                                "reply_operation_index",
                                AuditValue::Copy,
                            ),
                            AuditField::new("body_bytes", "body", AuditValue::Bytes),
                            AuditField::new(
                                "recipient_mode",
                                "recipient_agent_ids",
                                AuditValue::RecipientMode,
                            ),
                            AuditField::new("recipient_count", "recipient_agent_ids", AuditValue::Count),
                            AuditField::new(
                                "idempotency_key_present",
                                "idempotency_key",
                                AuditValue::StringPresent,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("message_id", "/message/message_id", AuditValue::Nullable),
                        AuditField::new(
                            "conversation_id",
                            "/message/conversation_id",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("seq", "/message/seq", AuditValue::Nullable),
                        AuditField::new(
                            "delivery_count",
                            "/message/deliveries",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new("replayed", "replayed", AuditValue::Nullable),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Atomically append one Message, recipient Deliveries, and a coalesced Wake. Exact replay cannot duplicate them; Agent authors require the current Endpoint generation. After commit, a registered exact Host adapter may receive one bounded continuation; otherwise the Wake stays pending.",
            post_conversation_message_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_agent_inbox",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new(
                                "after_delivery_order",
                                "after_delivery_order",
                                AuditValue::Copy,
                            ),
                            AuditField::new("limit", "limit", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("agent_id", "agent_id", AuditValue::Nullable),
                        AuditField::new(
                            "total_queued_count",
                            "total_queued_count",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("returned_count", "deliveries", AuditValue::NullableCount),
                        AuditField::new(
                            "after_delivery_order",
                            "after_delivery_order",
                            AuditValue::Nullable,
                        ),
                        AuditField::new(
                            "next_after_delivery_order",
                            "next_after_delivery_order",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("truncated", "truncated", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "List queued recipient-specific deliveries for an Agent proven by an active principal-bound Endpoint. Use after_delivery_order for bounded continuation. Offline Agents retain deliveries; reading does not consume them or invoke a model.",
            list_agent_inbox_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "consume_agent_deliveries",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new("delivery_count", "delivery_ids", AuditValue::Count),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("agent_id", "agent_id", AuditValue::Nullable),
                        AuditField::new(
                            "consumed_count",
                            "consumed_delivery_ids",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new(
                            "already_consumed_count",
                            "already_consumed_delivery_ids",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Mark exact deliveries consumed in an Agent Inbox proven by an active principal-bound Endpoint. This mutates recipient state only, never the append-only Message or Wake state. Repeating already-consumed ids is a safe desired-state retry.",
            consume_agent_deliveries_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "consume_agent_wake",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("agent_id", "agent_id", AuditValue::Copy),
                            AuditField::new("endpoint_id", "endpoint_id", AuditValue::Copy),
                            AuditField::new(
                                "expected_controller_generation",
                                "expected_controller_generation",
                                AuditValue::Copy,
                            ),
                            AuditField::new("wake_id", "wake_id", AuditValue::Copy),
                            AuditField::new(
                                "consume_token_present",
                                "consume_token",
                                AuditValue::ConsumeTokenPresent,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("wake_id", "wake_id", AuditValue::Nullable),
                        AuditField::new("target_agent_id", "target_agent_id", AuditValue::Nullable),
                        AuditField::new("state", "state", AuditValue::Nullable),
                        AuditField::new("already_consumed", "already_consumed", AuditValue::Nullable),
                        AuditField::new(
                            "consumed_at_unix_ms",
                            "consumed_at_unix_ms",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Consume one exact durable Agent Wake continuation after accepting the resumed model turn. wake_id and consume_token identify the exact continuation, while endpoint_id and expected_controller_generation fence stale attachments. Repeating the same exact consume returns already_consumed without another state change. This operation never consumes Agent Inbox deliveries and grants no Project, filesystem, Runner, Task, or Workflow Session authority.",
            consume_agent_wake_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
];
