use super::ToolVisibility::ModelVisible;
use super::{
    def, model_spec, permission_risk, require_all_scopes, ToolDefinition, PERMISSION_RISK_WRITE,
    TOOL_CATEGORY_COMMUNICATION,
};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{CommunicationManage, Read},
    COMMUNICATION_MANAGE, COMMUNICATION_READ, TOOL_PROVIDER_CONTROL,
};
use crate::registry::input_schemas::{
    attach_agent_endpoint_input_schema, bootstrap_agent_conversation_input_schema,
    consume_agent_deliveries_input_schema, consume_agent_wake_input_schema,
    create_agent_identity_input_schema, create_conversation_input_schema,
    detach_agent_endpoint_input_schema, list_agent_identities_input_schema,
    list_agent_inbox_input_schema, list_conversations_input_schema,
    post_conversation_message_input_schema, read_conversation_input_schema,
    update_agent_identity_input_schema,
};
use webcodex_core::authority::{COMMUNICATION_MANAGE_SCOPES, COMMUNICATION_READ_SCOPES};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        model_spec(
            def(
                "create_agent_identity",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent/agent_id"),
                    super::ToolAuditResultField::pointer("profile_revision", "/agent/profile_revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Create a durable Server-owned Agent identity and mutable self-description card. The canonical wc_dagent_* id is independent from windows, Endpoints, Workflow Sessions, Projects, and execution authority. Exact idempotency-key replay returns the original Agent; changed reuse is rejected.",
            create_agent_identity_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_agent_identities",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("total_count"),
                    super::ToolAuditResultField::array_len("returned_count", "agents"),
                    super::ToolAuditResultField::value("offset"),
                    super::ToolAuditResultField::value("next_offset"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "List bounded durable Agent cards owned by the current communication principal, or read one exact Agent. Handles, names, descriptions, labels, and Endpoint counts are metadata only and never grant Project, filesystem, Runner, or Workflow Session authority.",
            list_agent_identities_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "update_agent_identity",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent/agent_id"),
                    super::ToolAuditResultField::pointer("profile_revision", "/agent/profile_revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Update an owned Agent Card behind expected_profile_revision. Canonical agent_id never changes, and handle/display-name collisions remain allowed. On uncertain outcome, re-read the Agent instead of changing the revision fence blindly.",
            update_agent_identity_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "attach_agent_endpoint",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                    super::ToolAuditResultField::pointer_non_null("detached", "/endpoint/detached_at_unix_ms"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Attach a replacement Host/Client Endpoint to an owned durable Agent. The Server assigns a new monotonic controller generation and fences every older attachment. Public attachment is not wake-capable; only callable process-local Host adapter registration may enable continuation. Exact idempotency replay returns the original Endpoint.",
            attach_agent_endpoint_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "bootstrap_agent_conversation",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/acting_agent/agent_id"),
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("controller_generation", "/endpoint/controller_generation"),
                    super::ToolAuditResultField::pointer("conversation_id", "/selected_conversation/conversation_id"),
                    super::ToolAuditResultField::pointer("queued_delivery_count", "/inbox/queued_delivery_count"),
                    super::ToolAuditResultField::pointer("wake_id", "/wake/wake_id"),
                    super::ToolAuditResultField::pointer("wake_state", "/wake/state"),
                    super::ToolAuditResultField::pointer("adapter_kind", "/host_binding/adapter_kind"),
                    super::ToolAuditResultField::pointer("runtime_wake_capable", "/host_binding/runtime_wake_capable"),
                    super::ToolAuditResultField::pointer("production_auto_resume_available", "/host_binding/production_auto_resume_available"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Verify an exact Agent/Endpoint generation and return bounded turn context without Message bodies. With an activation idempotency key, accept one pending Wake into this already-active explicit turn and return a replayable consume token; this does not request a new model turn.",
            bootstrap_agent_conversation_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "detach_agent_endpoint",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                    super::ToolAuditResultField::pointer_non_null("detached", "/endpoint/detached_at_unix_ms"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Detach a principal-bound Agent Endpoint without deleting the durable Agent, Conversation transcript, or Inbox. Repeating the same detach is a safe desired-state retry; a new Endpoint may later attach the same agent_id.",
            detach_agent_endpoint_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "create_conversation",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("conversation_id", "/conversation/conversation/conversation_id"),
                    super::ToolAuditResultField::pointer_array_len("participant_count", "/conversation/participants"),
                    super::ToolAuditResultField::pointer_array_len("message_count", "/conversation/messages"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Create a durable Conversation containing the current Human principal and one or more owned Agents. Participation authorizes communication only, never Project, filesystem, Runner, Task, or Workflow Session execution. Exact idempotency-key replay returns the original Conversation.",
            create_conversation_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_conversations",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("total_count"),
                    super::ToolAuditResultField::array_len("returned_count", "conversations"),
                    super::ToolAuditResultField::value("offset"),
                    super::ToolAuditResultField::value("next_offset"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "List bounded Conversations visible to the current Human principal, or to an Agent proven by an active principal-bound Endpoint. Agent views include queued-delivery counts; listing never consumes Inbox state or invokes a model.",
            list_conversations_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "read_conversation",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("conversation_id", "/conversation/conversation_id"),
                    super::ToolAuditResultField::array_len("participant_count", "participants"),
                    super::ToolAuditResultField::array_len("message_count", "messages"),
                    super::ToolAuditResultField::value("after_seq"),
                    super::ToolAuditResultField::value("next_after_seq"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "Read a bounded ordered page from an append-only durable Conversation transcript, with participant and author provenance. Use after_seq for deterministic continuation. Reading does not consume recipient-specific Inbox deliveries or wake a model.",
            read_conversation_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "post_conversation_message",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("message_id", "/message/message_id"),
                    super::ToolAuditResultField::pointer("conversation_id", "/message/conversation_id"),
                    super::ToolAuditResultField::pointer("seq", "/message/seq"),
                    super::ToolAuditResultField::pointer_array_len("delivery_count", "/message/deliveries"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
            ),
            "Atomically append one Message, recipient Deliveries, and a coalesced Wake. Exact replay cannot duplicate them; Agent authors require the current Endpoint generation. After commit, a registered exact Host adapter may receive one bounded continuation; otherwise the Wake stays pending.",
            post_conversation_message_input_schema,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_agent_inbox",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::value("total_queued_count"),
                    super::ToolAuditResultField::array_len("returned_count", "deliveries"),
                    super::ToolAuditResultField::value("after_delivery_order"),
                    super::ToolAuditResultField::value("next_after_delivery_order"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "List queued recipient-specific deliveries for an Agent proven by an active principal-bound Endpoint. Use after_delivery_order for bounded continuation. Offline Agents retain deliveries; reading does not consume them or invoke a model.",
            list_agent_inbox_input_schema,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "consume_agent_deliveries",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::array_len("consumed_count", "consumed_delivery_ids"),
                    super::ToolAuditResultField::array_len("already_consumed_count", "already_consumed_delivery_ids"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Mark exact deliveries consumed in an Agent Inbox proven by an active principal-bound Endpoint. This mutates recipient state only, never the append-only Message or Wake state. Repeating already-consumed ids is a safe desired-state retry.",
            consume_agent_deliveries_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "consume_agent_wake",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("wake_id"),
                    super::ToolAuditResultField::value("target_agent_id"),
                    super::ToolAuditResultField::value("state"),
                    super::ToolAuditResultField::value("already_consumed"),
                    super::ToolAuditResultField::value("consumed_at_unix_ms"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
            ),
            "Consume one exact durable Agent Wake continuation after accepting the resumed model turn. wake_id and consume_token identify the exact continuation, while endpoint_id and expected_controller_generation fence stale attachments. Repeating the same exact consume returns already_consumed without another state change. This operation never consumes Agent Inbox deliveries and grants no Project, filesystem, Runner, Task, or Workflow Session authority.",
            consume_agent_wake_input_schema,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
];
