use super::ToolVisibility::ModelVisible;
use super::{
    adaptive_runtime_direct, context_recovery_only, def, model_spec, ToolDefinition,
    TOOL_CATEGORY_PROJECT, TOOL_CATEGORY_RUNTIME,
};
use crate::audit_policy::*;
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{ProjectWrite, Read},
    PROJECT_READ, PROJECT_WRITE, RUNTIME_READ, TOOL_PROVIDER_CONTROL,
};
use crate::registry::input_schemas::{
    create_project_input_schema, list_projects_input_schema, list_runners_input_schema,
    register_project_input_schema, runtime_status_input_schema, tool_manifest_input_schema,
    unregister_project_input_schema,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    context_recovery_only(model_spec(
        def(
            "list_projects",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("limit", "limit", AuditValue::Copy),
                        AuditField::new("summary_only", "summary_only", AuditValue::Copy),
                        AuditField::new("client_id_present", "client_id", AuditValue::Present),
                        AuditField::new("project_present", "project", AuditValue::Present),
                        AuditField::new("query_present", "query", AuditValue::StringPresent),
                        AuditField::new("query_length", "query", AuditValue::Chars),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Same,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "List caller-visible Projects. When Runner/Project identity is known, pass exact client_id/project; use bounded query and summary_only instead of reading the full registry.",
        list_projects_input_schema,
    )),
    model_spec(
        def(
            "register_project",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("client_id", "client_id", AuditValue::Copy),
                        AuditField::new("id", "id", AuditValue::Copy),
                        AuditField::new("name", "name", AuditValue::Copy),
                        AuditField::new("allow_patch", "allow_patch", AuditValue::Copy),
                        AuditField::new("overwrite", "overwrite", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            false,
            NoPath,
            true,
            false,
        ),
        "Register an existing directory, including a non-Git or ad-hoc workspace, as a Project on one Runner. Use this when the directory already exists; policy still bounds allowed paths.",
        register_project_input_schema,
    ),
    model_spec(
        def(
            "unregister_project",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("expected_revision", "expected_revision", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            false,
            NoPath,
            true,
            false,
        ),
        "Unregister one exact Runner project using the revision from list_projects. Removes registration only; never deletes source, worktree, or branch. Re-list after an indeterminate outcome.",
        unregister_project_input_schema,
    ),
    model_spec(
        def(
            "create_project",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("client_id", "client_id", AuditValue::Copy),
                        AuditField::new("id", "id", AuditValue::Copy),
                        AuditField::new("name", "name", AuditValue::Copy),
                        AuditField::new("allow_patch", "allow_patch", AuditValue::Copy),
                        AuditField::new("template", "template", AuditValue::Copy),
                        AuditField::new("git_init", "git_init", AuditValue::Copy),
                        AuditField::new(
                            "adopt_existing_empty",
                            "adopt_existing_empty",
                            AuditValue::Copy,
                        ),
                        AuditField::new("overwrite", "overwrite", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            false,
            NoPath,
            true,
            false,
        ),
        "Create a directory on one Runner and register it as a Project. Use this for a new workspace; existing directories belong on the registration path.",
        create_project_input_schema,
    ),
    context_recovery_only(model_spec(
        def(
            "list_runners",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("include_projects", "include_projects", AuditValue::Copy),
                        AuditField::new("summary_only", "summary_only", AuditValue::Copy),
                        AuditField::new("client_id_present", "client_id", AuditValue::Present),
                        AuditField::new("client_ids_count", "client_ids", AuditValue::Count),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides {
                        fields: &[],
                        omit: &["project"],
                    },
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "List caller-visible Runners; use exact client_id/client_ids if known, summary_only + include_projects=false for health. Full mode includes shared Job concurrency and host_context advisory metadata; never authority.",
        list_runners_input_schema,
    )),
    adaptive_runtime_direct(
        context_recovery_only(model_spec(
            def(
                "runtime_status",
                ToolAuditPolicy {
                    context: AuditContextPolicy::Omit,
                    execution: AuditExecutionPolicy::Omit,
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("compact", "compact", AuditValue::Copy),
                            AuditField::new("summary_only", "summary_only", AuditValue::Copy),
                            AuditField::new("client_id_present", "client_id", AuditValue::Present),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Overrides {
                            fields: &[],
                            omit: &["project"],
                        },
                    },
                    result: AuditResultPolicy::SessionEvidence,
                },
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(RUNTIME_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "Read runtime status; pass exact client_id for one Runner deployment/source alignment, omit for fleet-wide. Reports shared Job concurrency; global mode includes bounded host_context advisory metadata, never authority.",
            runtime_status_input_schema,
        )),
        20,
    ),
    adaptive_runtime_direct(
        context_recovery_only(model_spec(
            def(
                "tool_manifest",
                ToolAuditPolicy {
                    context: AuditContextPolicy::Omit,
                    execution: AuditExecutionPolicy::Omit,
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("tool_name", "tool_name", AuditValue::Copy),
                            AuditField::new("category", "category", AuditValue::Copy),
                            AuditField::new("intent", "intent", AuditValue::Copy),
                            AuditField::new(
                                "include_recommended_flows",
                                "include_recommended_flows",
                                AuditValue::Copy,
                            ),
                            AuditField::new(
                                "include_risk_summary",
                                "include_risk_summary",
                                AuditValue::Copy,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::SessionEvidence,
                },
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(RUNTIME_READ),
                false,
                NoPath,
                false,
                false,
            ),
            "Global runtime discovery; do not pass project. Filter by category/intent for sparse selection entries, or pass exact tool_name for one compact contract with description, route, input schema, and safety/authority hints but no output schema. If availability=direct, invoke that direct callable; if the host has not loaded it, rediscover/load it rather than routing it through call_runtime_tool. Unfiltered discovery retains the global category inventory. Discovery never changes behavior, authority, permissions, execution, or verdicts.",
            tool_manifest_input_schema,
        )),
        30,
    ),
];
