use super::RunnerCapabilityRequirement::GitOrShell;
use super::ToolVisibility::ModelVisible;
use super::{
    adaptive_runtime_direct, change_summary_like, context_recovery_only, def, git_like, model_spec,
    require_all_scopes, ToolDefinition, TOOL_CATEGORY_GIT,
};
use crate::audit_policy::*;
use crate::metadata::{
    ToolPathHint::{None as NoPath, PathList},
    ToolRisk::{ProjectWrite, Read},
    JOB_RUN, PROJECT_READ, PROJECT_WRITE, TOOL_PROVIDER_RUNNER,
};
use crate::registry::input_schemas::{
    git_commit_paths_input_schema, git_diff_hunks_input_schema, git_diff_input_schema,
    git_diff_summary_input_schema, git_log_input_schema, git_review_summary_input_schema,
    git_status_input_schema, show_changes_input_schema,
};

pub(super) const SUMMARY_DEFINITIONS: &[ToolDefinition] = &[
    context_recovery_only(change_summary_like(git_like(model_spec(
        def(
            "git_diff_summary",
            ToolAuditPolicy {
                context: AuditContextPolicy::Fields(&[
                    AuditField::new("clean", "clean", AuditValue::Copy),
                    AuditField::new("branch", "branch", AuditValue::Copy),
                    AuditField::new("head", "head", AuditValue::Copy),
                    AuditField::new("upstream", "upstream", AuditValue::Copy),
                    AuditField::new("ahead", "ahead", AuditValue::Copy),
                    AuditField::new("behind", "behind", AuditValue::Copy),
                    AuditField::new("counts", "counts", AuditValue::Copy),
                    AuditField::new("changed_files", "changed_files", AuditValue::Copy),
                ]),
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[AuditField::new("project", "project", AuditValue::Copy)],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Same,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_GIT,
            Some(GitOrShell),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Read-only git diff summary for a project: `git status --porcelain`, `git diff --stat`, and a parsed changed-file list. Does not modify the worktree.",
        git_diff_summary_input_schema,
    )))),
    adaptive_runtime_direct(
        context_recovery_only(change_summary_like(git_like(model_spec(
            def(
                "git_review_summary",
                ToolAuditPolicy {
                    context: AuditContextPolicy::Omit,
                    execution: AuditExecutionPolicy::Omit,
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("base_commit", "base_commit", AuditValue::ExactCommit),
                            AuditField::new("head_commit", "head_commit", AuditValue::ExactCommit),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("project", "project", AuditValue::Nullable),
                        AuditField::new("scope", "scope", AuditValue::Nullable),
                        AuditField::new("stats", "stats", AuditValue::Nullable),
                        AuditField::new("coverage", "coverage", AuditValue::Nullable),
                        AuditField::new("truncation", "truncation", AuditValue::Nullable),
                        AuditField::new("deterministic", "deterministic", AuditValue::Nullable),
                        AuditField::new("llm_summary", "llm_summary", AuditValue::Nullable),
                        AuditField::new("truncated", "truncated", AuditValue::Nullable),
                        AuditField::new("reason_code", "reason_code", AuditValue::Nullable),
                        AuditField::new("signal_count", "signals", AuditValue::NullableCount),
                        AuditField::new("file_count", "files", AuditValue::NullableCount),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_GIT,
                Some(GitOrShell),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
            ),
            "Deterministic bounded committed-range review map. Use before targeted git_diff_hunks/read_files during branch or PR review. Does not judge correctness and never mutates the repository.",
            git_review_summary_input_schema,
        )))),
        120,
    ),
    adaptive_runtime_direct(
        context_recovery_only(change_summary_like(git_like(model_spec(
            def(
                "show_changes",
                ToolAuditPolicy {
                    context: AuditContextPolicy::Fields(&[
                        AuditField::new("clean", "clean", AuditValue::Copy),
                        AuditField::new("branch", "branch", AuditValue::Copy),
                        AuditField::new("head", "head", AuditValue::Copy),
                        AuditField::new("upstream", "upstream", AuditValue::Copy),
                        AuditField::new("ahead", "ahead", AuditValue::Copy),
                        AuditField::new("behind", "behind", AuditValue::Copy),
                        AuditField::new("counts", "counts", AuditValue::Copy),
                        AuditField::new("changed_files", "changed_files", AuditValue::Copy),
                    ]),
                    execution: AuditExecutionPolicy::Omit,
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("include_diff", "include_diff", AuditValue::Copy),
                            AuditField::new("max_hunks", "max_hunks", AuditValue::Copy),
                            AuditField::new("max_hunk_lines", "max_hunk_lines", AuditValue::Copy),
                            AuditField::new(
                                "session_event_limit",
                                "session_event_limit",
                                AuditValue::Copy,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::SessionEvidence,
                },
                ModelVisible,
                TOOL_CATEGORY_GIT,
                Some(GitOrShell),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
            ),
            "Default inspect/review tool before final response. Read-only worktree overview with bounded hunks. If hunks truncate, diff_review_handoff classifies page/line/mixed truncation and provides a parser-ready git_diff_hunks recovery call.",
            show_changes_input_schema,
        )))),
        130,
    ),
];

pub(super) const DETAIL_DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(git_like(model_spec(
        def(
            "git_commit_paths",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("paths", "paths", AuditValue::Copy),
                        AuditField::new("message_present", "message", AuditValue::StringPresent),
                        AuditField::new("expected_head", "expected_head", AuditValue::ExactCommit),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Same,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_GIT,
            Some(GitOrShell),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            PathList,
            false,
            false,
        ),
        "Commit exactly requested changed file paths with an atomic expected_head fence and isolated temporary index; normal Git clean filters may run under job:run authority, ordinary commit hooks are bypassed so they cannot add unrelated paths, and the tool never pushes.",
        git_commit_paths_input_schema,
    )), &[PROJECT_WRITE, JOB_RUN]),
    context_recovery_only(git_like(model_spec(
        def(
            "git_status",
            ToolAuditPolicy {
                context: AuditContextPolicy::WorkingTreeStatus,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[AuditField::new("project", "project", AuditValue::Copy)],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Same,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_GIT,
            Some(GitOrShell),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Run git status --porcelain for a project.",
        git_status_input_schema,
    ))),
    context_recovery_only(git_like(model_spec(
        def(
            "git_diff",
            ToolAuditPolicy {
                context: AuditContextPolicy::Omit,
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("args_count", "args", AuditValue::OptionalCount),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides {
                        fields: &[AuditField::new(
                            "args_count",
                            "args",
                            AuditValue::NullableCount,
                        )],
                        omit: &[],
                    },
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_GIT,
            Some(GitOrShell),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Run git diff for a project, optionally scoped to paths.",
        git_diff_input_schema,
    ))),
    adaptive_runtime_direct(
        context_recovery_only(change_summary_like(git_like(model_spec(
            def(
                "git_diff_hunks",
                ToolAuditPolicy {
                    context: AuditContextPolicy::Omit,
                    execution: AuditExecutionPolicy::Omit,
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("paths", "paths", AuditValue::Copy),
                            AuditField::new("max_hunks", "max_hunks", AuditValue::Copy),
                            AuditField::new("max_hunk_lines", "max_hunk_lines", AuditValue::Copy),
                            AuditField::new("cached", "cached", AuditValue::Copy),
                            AuditField::new("continuation_present", "continuation", AuditValue::Present),
                            AuditField::new("base_commit", "base_commit", AuditValue::ExactCommit),
                            AuditField::new("head_commit", "head_commit", AuditValue::ExactCommit),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Overrides {
                            fields: &[],
                            omit: &[
                                "continuation_present",
                                "base_commit",
                                "head_commit",
                                "base_commit_valid",
                                "head_commit_valid",
                            ],
                        },
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("project", "project", AuditValue::Nullable),
                        AuditField::new("scope", "scope", AuditValue::Nullable),
                        AuditField::new("cached", "cached", AuditValue::Nullable),
                        AuditField::new("hunk_count", "hunk_count", AuditValue::Nullable),
                        AuditField::new("truncated", "truncated", AuditValue::Nullable),
                        AuditField::new(
                            "truncation_reasons",
                            "truncation_reasons",
                            AuditValue::Nullable,
                        ),
                        AuditField::new("has_more", "has_more", AuditValue::Nullable),
                        AuditField::new("exit_code", "exit_code", AuditValue::Nullable),
                        AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                        AuditField::new("reason_code", "reason_code", AuditValue::Nullable),
                        AuditField::new("file_count", "files", AuditValue::NullableCount),
                    ]),
                },
                ModelVisible,
                TOOL_CATEGORY_GIT,
                Some(GitOrShell),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
            ),
            "Targeted/paged diff review for worktree/cached or exact base/head ranges, with paths and scope-bound opaque continuation. Replay scope and paging inputs unchanged for later records. Truncated results separate later-hunk continuation from omitted_lines recoverability: hunk_line_limit can use larger max_hunk_lines and/or narrower paths only with bounded headroom; fixed byte/line ceilings never advertise fake recovery. Read-only.",
            git_diff_hunks_input_schema,
        )))),
        125,
    ),
    context_recovery_only(git_like(model_spec(
        def(
            "git_log",
            ToolAuditPolicy {
                context: AuditContextPolicy::Fields(&[
                    AuditField::new("commits", "commits", AuditValue::Copy),
                    AuditField::new("next_skip", "next_skip", AuditValue::Copy),
                    AuditField::new("truncated", "truncated", AuditValue::Copy),
                ]),
                execution: AuditExecutionPolicy::Omit,
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("limit", "limit", AuditValue::Copy),
                        AuditField::new("skip", "skip", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Same,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_GIT,
            Some(GitOrShell),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Return bounded structured recent git commit history for a project. Does not return commit bodies or modify the worktree.",
        git_log_input_schema,
    ))),
];
