use super::ToolVisibility::ModelHidden;
use super::{def, require_all_scopes, ToolDefinition, TOOL_CATEGORY_RUNTIME};
use crate::audit_policy::*;
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{MemoryManage, Read},
    ADMIN, PROJECT_READ, PROJECT_WRITE, TOOL_PROVIDER_CONTROL,
};
use webcodex_core::authority::{MEMORY_MANAGE_SCOPES, MEMORY_READ_SCOPES};

/// Fixed Control-owned project Memory runtime contract. These tools remain
/// globally hidden and are projected only by the capable Stateless MCP Full
/// Operator surface; the kernel capability gate is authoritative.
pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        def(
            "memory_search",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("offset", "offset", AuditValue::Copy),
                        AuditField::new("limit", "limit", AuditValue::Copy),
                        AuditField::new(
                            "expected_catalog_revision",
                            "expected_catalog_revision",
                            AuditValue::Copy,
                        ),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("query_present", "query", AuditValue::NonemptyString),
                        AuditField::new("tag_count", "tags", AuditValue::Count),
                    ],
                    transform: AuditTransform::Fields,
                    typed_fields: &[],
                    typed_omit: &[],
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("project", "project", AuditValue::Nullable),
                    AuditField::new("catalog_revision", "catalog_revision", AuditValue::Nullable),
                    AuditField::new("total_count", "total_count", AuditValue::Nullable),
                    AuditField::new("returned_count", "returned_count", AuditValue::Nullable),
                    AuditField::new("truncated", "truncated", AuditValue::Nullable),
                    AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                ]),
            },
            ModelHidden,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        MEMORY_READ_SCOPES,
    ),
    require_all_scopes(
        def(
            "memory_read",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("memory_key", "memory_key", AuditValue::Copy),
                        AuditField::new("expected_revision", "expected_revision", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed_fields: &[],
                    typed_omit: &[],
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("project", "project", AuditValue::Nullable),
                    AuditField::new("memory_id", "memory_id", AuditValue::Nullable),
                    AuditField::new("memory_key", "memory_key", AuditValue::Nullable),
                    AuditField::new("revision", "revision", AuditValue::Nullable),
                    AuditField::new("bootstrap", "bootstrap", AuditValue::Nullable),
                    AuditField::new("priority", "priority", AuditValue::Nullable),
                    AuditField::new("returned_body_bytes", "body", AuditValue::NullableBytes),
                    AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                ]),
            },
            ModelHidden,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        MEMORY_READ_SCOPES,
    ),
    require_all_scopes(
        def(
            "memory_set",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("memory_key", "memory_key", AuditValue::Copy),
                        AuditField::new("priority", "priority", AuditValue::Copy),
                        AuditField::new("bootstrap", "bootstrap", AuditValue::Copy),
                        AuditField::new("expected_revision", "expected_revision", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("summary_present", "summary", AuditValue::StringPresent),
                        AuditField::new("body_present", "body", AuditValue::StringPresent),
                        AuditField::new("tag_count", "tags", AuditValue::Count),
                    ],
                    transform: AuditTransform::Fields,
                    typed_fields: &[],
                    typed_omit: &[],
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("project", "project", AuditValue::Nullable),
                    AuditField::new("memory_id", "memory_id", AuditValue::Nullable),
                    AuditField::new("memory_key", "memory_key", AuditValue::Nullable),
                    AuditField::new("old_revision", "old_revision", AuditValue::Nullable),
                    AuditField::new("revision", "revision", AuditValue::Nullable),
                    AuditField::new("created", "created", AuditValue::Nullable),
                    AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                ]),
            },
            ModelHidden,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: MemoryManage,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            false,
            false,
        ),
        MEMORY_MANAGE_SCOPES,
    ),
    require_all_scopes(
        def(
            "memory_delete",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("memory_key", "memory_key", AuditValue::Copy),
                        AuditField::new("expected_revision", "expected_revision", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed_fields: &[],
                    typed_omit: &[],
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("project", "project", AuditValue::Nullable),
                    AuditField::new("memory_id", "memory_id", AuditValue::Nullable),
                    AuditField::new("memory_key", "memory_key", AuditValue::Nullable),
                    AuditField::new("revision", "revision", AuditValue::Nullable),
                    AuditField::new("deleted", "deleted", AuditValue::Nullable),
                    AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                    AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
                ]),
            },
            ModelHidden,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: MemoryManage,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            true,
            false,
        ),
        MEMORY_MANAGE_SCOPES,
    ),
    def(
        "memory_scope_list",
        ToolAuditPolicy {
            request: AuditRequestPolicy {
                fields: &[
                    AuditField::new("project", "project", AuditValue::Copy),
                    AuditField::new("offset", "offset", AuditValue::Copy),
                    AuditField::new("limit", "limit", AuditValue::Copy),
                ],
                transform: AuditTransform::Fields,
                typed_fields: &[],
                typed_omit: &[],
            },
            result: AuditResultPolicy::Fields(&[
                AuditField::new("total_count", "total_count", AuditValue::Nullable),
                AuditField::new("returned_count", "returned_count", AuditValue::Nullable),
                AuditField::new("truncated", "truncated", AuditValue::Nullable),
                AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
            ]),
        },
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(ADMIN),
        false,
        NoPath,
        false,
        false,
    ),
    def(
        "memory_scope_purge",
        ToolAuditPolicy {
            request: AuditRequestPolicy {
                fields: &[
                    AuditField::new("project", "project", AuditValue::Copy),
                    AuditField::new("memory_scope_id", "memory_scope_id", AuditValue::Copy),
                    AuditField::new(
                        "expected_catalog_revision",
                        "expected_catalog_revision",
                        AuditValue::Copy,
                    ),
                ],
                transform: AuditTransform::Fields,
                typed_fields: &[],
                typed_omit: &[],
            },
            result: AuditResultPolicy::Fields(&[
                AuditField::new("memory_scope_id", "memory_scope_id", AuditValue::Nullable),
                AuditField::new("catalog_revision", "catalog_revision", AuditValue::Nullable),
                AuditField::new(
                    "current_catalog_revision",
                    "current_catalog_revision",
                    AuditValue::Nullable,
                ),
                AuditField::new("purged_count", "purged_count", AuditValue::Nullable),
                AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                AuditField::new("state_changed", "state_changed", AuditValue::Nullable),
            ]),
        },
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: MemoryManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        false,
        NoPath,
        true,
        false,
    ),
];
