use super::RunnerCapabilityRequirement::{GitOrShell, OwnerOnly};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, context_recovery_only, context_reobservable, def, model_spec,
    permission_risk, requires_explicit_business_session, ToolDefinition, PERMISSION_RISK_WRITE,
    TOOL_CATEGORY_SESSION, TOOL_CATEGORY_VALIDATION,
};
use crate::metadata::{
    ToolPathHint::None as NoPath, ToolRisk::Read, PROJECT_READ, PROJECT_WRITE, RUNTIME_READ,
    SESSION_COLLABORATE, TOOL_PROVIDER_CONTROL,
};
use crate::registry::input_schemas::{
    close_session_input_schema, complete_session_message_input_schema,
    finish_coding_task_input_schema, get_session_assignment_input_schema,
    list_session_messages_input_schema, observe_session_messages_input_schema,
    post_session_message_input_schema, resolve_session_message_input_schema,
    session_discussion_summary_input_schema, session_handoff_summary_input_schema,
    session_summary_input_schema, update_session_context_input_schema,
    validation_summary_input_schema, work_on_project_input_schema,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    def(
        "start_session",
        super::ToolAuditPolicy::TYPED_CANONICAL,
        ModelHidden,
        TOOL_CATEGORY_SESSION,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::WorkflowManage,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    ),
    adaptive_runtime_direct(
        context_reobservable(model_spec(
            def(
                "work_on_project",
                super::ToolAuditPolicy::TYPED_CANONICAL,
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: super::ToolRisk::WorkflowManage,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Canonical bootstrap for ordinary coding/review. Use project or client_id+path. Omit session_id for a fresh Workflow Session; supply it for exact resume of an active accessible Session; never guesses prior Session. Defaults return bounded project instructions, workflow guidance, and Skills/Plugin selection metadata, which grants no authority. Skill bodies require skill_read_file; Plugin calls require plugin_tool describe. Set include_* false only when the current model context retains that material; Session/window/transport/credential/Server identity never proves retention. Fresh contexts keep defaults true on resume; include_extension_catalog=false skips discovery. Checkout accepts Project or Runner path and does not require Git; mode=worktree resolves an exact Git base and manages an isolated worktree without bypassing Project authority.",
            work_on_project_input_schema,
        )),
        10,
    ),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "finish_coding_task",
                super::ToolAuditPolicy::TYPED_CANONICAL,
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Return an optional deterministic evidence snapshot for model review, including workspace, validation, jobs, and recorded tool events. The result is advisory: it does not decide task completion, replace direct diff or test review, or generate the user-facing final report.",
            finish_coding_task_input_schema,
        )),
        150,
    ),
    requires_explicit_business_session(context_reobservable(model_spec(
        def(
            "session_summary",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Return a bounded structured summary from the session ledger for an explicit session_id: recorded events, message-board summary, task mode, guards, and lifecycle. Uses durable ledger data where session persistence is configured.",
        session_summary_input_schema,
    ))),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "update_session_context",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Update Session defaults. Binding execution_context.resource selects an already active Runner-local named SSH resource; for a new explicit target use ssh_resource list/register and restart the Runner first, then list and bind the active name. open_session_shell uses that Session binding. Requires an authorized project matching the exact Session project; cross-project escape is not supported. Context and event commit under the store lock; the background writer persists, so success does not mean disk flush. Never falls back and never creates unknown Sessions.",
            update_session_context_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "close_session",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.persistent_shell(super::PersistentShellEvidenceAction::Close).lifecycle(super::ToolSessionLifecycleEffect::IdempotentClose),
            ),
            "Explicitly close a workflow session (Active to Closed) for a required session_id. Query remains available; write/shell/mutation tools are denied. Idempotent when already closed; unknown ids fail without create. finish_coding_task does not close.",
            close_session_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(context_reobservable(model_spec(
        def(
            "validation_summary",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_VALIDATION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Read bounded structured validation evidence already recorded in an explicit project-scoped session ledger. Does not run Cargo or shell commands, enqueue a Runner request, read project files, mutate the workspace, or replace finish_coding_task.",
        validation_summary_input_schema,
    ))),
    requires_explicit_business_session(model_spec(
        def(
            "post_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::pointer("kind", "/message/kind"),
                super::ToolAuditResultField::pointer("status", "/message/status"),
                super::ToolAuditResultField::pointer("requires_ack", "/message/requires_ack"),
                super::ToolAuditResultField::pointer("author_session_id", "/message/author_session_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
        ),
        "Post a bounded collaboration message (todo, question, progress, guidance, risk, or decision). High-priority guidance may require request-scoped ACK; ACK neither resolves nor gates work. Use complete_session_message to atomically answer and resolve a finished todo.",
        post_session_message_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "list_session_messages",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::array_len("message_count", "messages"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Read bounded session-local messages with exact filters. For an executable todo, prefer get_session_assignment so the todo, all retained direct replies, and its completion fence come from one store snapshot.",
        list_session_messages_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "get_session_assignment",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::array_len("direct_reply_count", "direct_replies"),
                super::ToolAuditResultField::string_present("assignment_fence_present", "assignment_fence"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Atomically read one exact open todo plus all retained direct replies and return the opaque assignment_fence required by complete_session_message. Unrelated Session traffic and ACK bookkeeping do not stale it; incomplete retained assignment history fails closed.",
        get_session_assignment_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "observe_session_messages",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::array_len("message_count", "messages"),
                super::ToolAuditResultField::value("changed"),
                super::ToolAuditResultField::value("history_lost"),
                super::ToolAuditResultField::value("has_more"),
                super::ToolAuditResultField::value("wait_outcome"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Observe Session message-state delta after an opaque durable cursor. No token establishes the current baseline and returns no history; token calls may wait once for change. Reports retention loss; never a subscription, delivery receipt, or model-context proof.",
        observe_session_messages_input_schema,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "resolve_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::pointer("status", "/message/status"),
                super::ToolAuditResultField::pointer("resolved_by_message_id", "/message/resolved_by_message_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Mark a session-local ledger message resolved. Idempotent when the message is already resolved; metadata-only and never modifies project files.",
            resolve_session_message_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "complete_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::value("answer_message_id"),
                super::ToolAuditResultField::value("completion_id"),
                super::ToolAuditResultField::value("replayed"),
                super::ToolAuditResultField::pointer("author_session_id", "/answer/author_session_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::FencedReplay,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Atomically answer and resolve one exact open todo. expected_assignment_fence is required and must be the exact opaque fence from get_session_assignment; completion_key separately keeps uncertain-result retries idempotent.",
            complete_session_message_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "session_discussion_summary",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("success"),
                    super::ToolAuditResultField::value("session_id"),
                    super::ToolAuditResultField::value("counts"),
                    super::ToolAuditResultField::array_len("open_todo_count", "open_todos"),
                    super::ToolAuditResultField::array_len("recent_answer_count", "recent_answers"),
                    super::ToolAuditResultField::array_len("recent_completion_count", "recent_completions"),
                ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Return a bounded structured aggregate of session-local discussion from the recorded session ledger. Does not call an LLM or generate natural-language summaries.",
            session_discussion_summary_input_schema,
        )),
        15,
    ),
    requires_explicit_business_session(context_recovery_only(model_spec(
        def(
            "session_handoff_summary",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("project"),
                super::ToolAuditResultField::value("lifecycle"),
                super::ToolAuditResultField::value("counts"),
                super::ToolAuditResultField::array_len("open_todo_count", "open_todos"),
                super::ToolAuditResultField::array_len("recent_answer_count", "recent_answers"),
                super::ToolAuditResultField::array_len("recent_completion_count", "recent_completions"),
                super::ToolAuditResultField::value("summary_only"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Read-only handoff for multi-step tasks, explicit session_id. Reads session ledger collaboration and ledger-derived validation. Diagnostics use bounded tails or safe result metadata; validation.parser.available is false if absent. Use the default full view to recover unknown context; summary_only, limit below 20, or disabled include_* components cannot establish a new ACK baseline. No checkpoint allocation; grants no authority.",
        session_handoff_summary_input_schema,
    ))),
];
