use super::RunnerCapabilityRequirement::{GitOrShell, OwnerOnly};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, context_recovery_only, def, model_spec, permission_risk,
    requires_explicit_business_session, ToolDefinition, PERMISSION_RISK_WRITE,
    TOOL_CATEGORY_SESSION, TOOL_CATEGORY_VALIDATION,
};
use crate::audit_policy::*;
use crate::metadata::{
    ToolPathHint::None as NoPath, ToolRisk::Read, PROJECT_READ, PROJECT_WRITE, RUNTIME_READ,
    SESSION_COLLABORATE, TOOL_PROVIDER_CONTROL,
};
use crate::registry::input_schemas::{
    close_session_input_schema, complete_session_message_input_schema,
    finish_coding_task_input_schema, get_session_assignment_input_schema,
    list_session_messages_input_schema, observe_session_messages_input_schema,
    post_session_message_input_schema, resolve_session_message_input_schema,
    session_discussion_summary_input_schema, session_handoff_summary_input_schema,
    session_summary_input_schema, update_session_context_input_schema,
    validation_summary_input_schema, work_on_project_input_schema,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    def(
        "start_session",
        ToolAuditPolicy {
            request: AuditRequestPolicy {
                fields: &[
                    AuditField::new("project", "project", AuditValue::Copy),
                    AuditField::new("client_id", "client_id", AuditValue::Copy),
                    AuditField::new("title", "title", AuditValue::Copy),
                    AuditField::new("mode", "mode", AuditValue::Copy),
                    AuditField::new("deny_write_tools", "deny_write_tools", AuditValue::Copy),
                    AuditField::new("deny_shell_tools", "deny_shell_tools", AuditValue::Copy),
                    AuditField::new("detail", "detail", AuditValue::Copy),
                    AuditField::new("resume_session_id", "resume_session_id", AuditValue::Copy),
                    AuditField::new("session_id", "session_id", AuditValue::Copy),
                    AuditField::new(
                        "execution_context",
                        "execution_context",
                        AuditValue::ExecutionContext,
                    ),
                ],
                transform: AuditTransform::Fields,
                typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["client_id", "detail", "resume_session_id", "session_id"] },
            },
            result: AuditResultPolicy::SessionEvidence,
        },
        ModelHidden,
        TOOL_CATEGORY_SESSION,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::WorkflowManage,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    adaptive_runtime_direct(
        context_recovery_only(model_spec(
            def(
                "work_on_project",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("client_id", "client_id", AuditValue::Copy),
                            AuditField::new("session_id", "session_id", AuditValue::Copy),
                            AuditField::new(
                                "include_project_instructions",
                                "include_project_instructions",
                                AuditValue::Copy,
                            ),
                            AuditField::new(
                                "include_workflow_guidance",
                                "include_workflow_guidance",
                                AuditValue::Copy,
                            ),
                            AuditField::new("path_source_requested", "path", AuditValue::KeyPresent),
                            AuditField::new("instruction_summary", "instruction", AuditValue::Preview),
                            AuditField::new(
                                "instruction_present",
                                "instruction",
                                AuditValue::StringPresent,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Overrides { fields: &[
                            AuditField::new("mode", "mode", AuditValue::Copy),
                            AuditField::new("base_ref_present", "base_ref", AuditValue::Present),
                            AuditField::new("path_source_requested", "path", AuditValue::Present),
                        ], omit: &[] },
                    },
                    result: AuditResultPolicy::SessionEvidence,
                },
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: super::ToolRisk::WorkflowManage,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
            ),
            "Canonical model entry for ordinary coding/review via an existing Project or Runner path; Git not required for checkout mode. Omitted/checkout preserves the existing path flow. mode=worktree with client_id + path asks the Runner to resolve an exact Git base, bootstrap or re-observe an isolated managed worktree, register it as an ordinary Project, and then start or exactly resume the Workflow Session. This hides registration/worktree plumbing without bypassing Project authority and returns compact workflow plus project instructions.",
            work_on_project_input_schema,
        )),
        10,
    ),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "finish_coding_task",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("session_id", "session_id", AuditValue::Copy),
                            AuditField::new("summary_only", "summary_only", AuditValue::Copy),
                            AuditField::new("include_diff", "include_diff", AuditValue::Copy),
                            AuditField::new("include_workspace", "include_workspace", AuditValue::Copy),
                            AuditField::new("include_hygiene", "include_hygiene", AuditValue::Copy),
                            AuditField::new("include_handoff", "include_handoff", AuditValue::Copy),
                            AuditField::new(
                                "include_validation_summary",
                                "include_validation_summary",
                                AuditValue::Copy,
                            ),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Same,
                    },
                    result: AuditResultPolicy::SessionEvidence,
                },
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
            ),
            "Return an optional deterministic evidence snapshot for model review, including workspace, validation, jobs, and recorded tool events. The result is advisory: it does not decide task completion, replace direct diff or test review, or generate the user-facing final report.",
            finish_coding_task_input_schema,
        )),
        150,
    ),
    requires_explicit_business_session(model_spec(
        def(
            "session_summary",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
AuditField::new("session_id", "session_id", AuditValue::Copy),
AuditField::new("limit", "limit", AuditValue::Copy),
],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Return a bounded structured summary from the session ledger for an explicit session_id: recorded events, message-board summary, task mode, guards, and lifecycle. Uses durable ledger data where session persistence is configured.",
        session_summary_input_schema,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "update_session_context",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("client_id", "client_id", AuditValue::Copy),
                        AuditField::new("title", "title", AuditValue::Copy),
                        AuditField::new("mode", "mode", AuditValue::Copy),
                        AuditField::new("deny_write_tools", "deny_write_tools", AuditValue::Copy),
                        AuditField::new("deny_shell_tools", "deny_shell_tools", AuditValue::Copy),
                        AuditField::new("detail", "detail", AuditValue::Copy),
                        AuditField::new("resume_session_id", "resume_session_id", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new(
                            "execution_context",
                            "execution_context",
                            AuditValue::ExecutionContext,
                        ),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides { fields: &[], omit: &[
                        "client_id",
                        "title",
                        "mode",
                        "deny_write_tools",
                        "deny_shell_tools",
                        "detail",
                        "resume_session_id",
                    ] },
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            true,
            false,
            ),
            "Update Session defaults. Binding execution_context.resource selects an already active Runner-local named SSH resource; for a new explicit target use ssh_resource list/register and restart the Runner first, then list and bind the active name. open_session_shell uses that Session binding. Requires an authorized project matching the exact Session project; cross-project escape is not supported. Context and event commit under the store lock; the background writer persists, so success does not mean disk flush. Never falls back and never creates unknown Sessions.",
            update_session_context_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "close_session",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
AuditField::new("session_id", "session_id", AuditValue::Copy),
],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            ),
            "Explicitly close a workflow session (Active to Closed) for a required session_id. Query remains available; write/shell/mutation tools are denied. Idempotent when already closed; unknown ids fail without create. finish_coding_task does not close.",
            close_session_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "validation_summary",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
AuditField::new("project", "project", AuditValue::Copy),
AuditField::new("session_id", "session_id", AuditValue::Copy),
AuditField::new("limit", "limit", AuditValue::Copy),
],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::SessionEvidence,
            },
            ModelVisible,
            TOOL_CATEGORY_VALIDATION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Read bounded structured validation evidence already recorded in an explicit project-scoped session ledger. Does not run Cargo or shell commands, enqueue a Runner request, read project files, mutate the workspace, or replace finish_coding_task.",
        validation_summary_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "post_session_message",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("kind", "kind", AuditValue::Copy),
                        AuditField::new("reply_to", "reply_to", AuditValue::Copy),
                        AuditField::new("priority", "priority", AuditValue::Copy),
                        AuditField::new("requires_ack", "requires_ack", AuditValue::Copy),
                        AuditField::new("body_present", "message", AuditValue::StringPresent),
                        AuditField::new("body_bytes", "message", AuditValue::Bytes),
                        AuditField::new("tags_count", "tags", AuditValue::Count),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["project"] },
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("success", "success", AuditValue::Nullable),
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("message_id", "message_id", AuditValue::Nullable),
                    AuditField::new("kind", "/message/kind", AuditValue::Nullable),
                    AuditField::new("status", "/message/status", AuditValue::Nullable),
                    AuditField::new(
                        "requires_ack",
                        "/message/requires_ack",
                        AuditValue::Nullable,
                    ),
                    AuditField::new(
                        "author_session_id",
                        "/message/author_session_id",
                        AuditValue::Nullable,
                    ),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
        ),
        "Post a bounded collaboration message (todo, question, progress, guidance, risk, or decision). High-priority guidance may require request-scoped ACK; ACK neither resolves nor gates work. Use complete_session_message to atomically answer and resolve a finished todo.",
        post_session_message_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "list_session_messages",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("kind", "kind", AuditValue::Copy),
                        AuditField::new("status", "status", AuditValue::Copy),
                        AuditField::new("message_id", "message_id", AuditValue::Copy),
                        AuditField::new("reply_to", "reply_to", AuditValue::Copy),
                        AuditField::new("limit", "limit", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["project"] },
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("success", "success", AuditValue::Nullable),
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("message_count", "messages", AuditValue::NullableCount),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Read bounded session-local messages with exact filters. For an executable todo, prefer get_session_assignment so the todo, all retained direct replies, and its completion fence come from one store snapshot.",
        list_session_messages_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "get_session_assignment",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("message_id", "message_id", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Omit,
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("success", "success", AuditValue::Nullable),
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("message_id", "message_id", AuditValue::Nullable),
                    AuditField::new(
                        "direct_reply_count",
                        "direct_replies",
                        AuditValue::NullableCount,
                    ),
                    AuditField::new(
                        "assignment_fence_present",
                        "assignment_fence",
                        AuditValue::StringPresent,
                    ),
                    AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Atomically read one exact open todo plus all retained direct replies and return the opaque assignment_fence required by complete_session_message. Unrelated Session traffic and ACK bookkeeping do not stale it; incomplete retained assignment history fails closed.",
        get_session_assignment_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "observe_session_messages",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("wait_secs", "wait_secs", AuditValue::Copy),
                        AuditField::new("limit", "limit", AuditValue::Copy),
                        AuditField::new(
                            "token_present",
                            "after_observation_token",
                            AuditValue::StringPresent,
                        ),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["project"] },
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("success", "success", AuditValue::Nullable),
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("message_count", "messages", AuditValue::NullableCount),
                    AuditField::new("changed", "changed", AuditValue::Nullable),
                    AuditField::new("history_lost", "history_lost", AuditValue::Nullable),
                    AuditField::new("has_more", "has_more", AuditValue::Nullable),
                    AuditField::new("wait_outcome", "wait_outcome", AuditValue::Nullable),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Observe Session message-state delta after an opaque durable cursor. No token establishes the current baseline and returns no history; token calls may wait once for change. Reports retention loss; never a subscription, delivery receipt, or model-context proof.",
        observe_session_messages_input_schema,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "resolve_session_message",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("message_id", "message_id", AuditValue::Copy),
                        AuditField::new(
                            "resolution_present",
                            "resolution",
                            AuditValue::StringPresent,
                        ),
                        AuditField::new("resolution_bytes", "resolution", AuditValue::Bytes),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["project", "resolution_bytes"] },
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("success", "success", AuditValue::Nullable),
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("message_id", "message_id", AuditValue::Nullable),
                    AuditField::new("status", "/message/status", AuditValue::Nullable),
                    AuditField::new(
                        "resolved_by_message_id",
                        "/message/resolved_by_message_id",
                        AuditValue::Nullable,
                    ),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            ),
            "Mark a session-local ledger message resolved. Idempotent when the message is already resolved; metadata-only and never modifies project files.",
            resolve_session_message_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "complete_session_message",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("message_id", "message_id", AuditValue::Copy),
                        AuditField::new("priority", "priority", AuditValue::Copy),
                        AuditField::new("body_present", "answer", AuditValue::StringPresent),
                        AuditField::new("body_bytes", "answer", AuditValue::Bytes),
                        AuditField::new("tags_count", "tags", AuditValue::Count),
                        AuditField::new(
                            "completion_id",
                            "completion_key",
                            AuditValue::CompletionFingerprint,
                        ),
                        AuditField::new(
                            "assignment_fence_present",
                            "expected_assignment_fence",
                            AuditValue::StringPresent,
                        ),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["project", "assignment_fence_present"] },
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("success", "success", AuditValue::Nullable),
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("message_id", "message_id", AuditValue::Nullable),
                    AuditField::new(
                        "answer_message_id",
                        "answer_message_id",
                        AuditValue::Nullable,
                    ),
                    AuditField::new("completion_id", "completion_id", AuditValue::Nullable),
                    AuditField::new("replayed", "replayed", AuditValue::Nullable),
                    AuditField::new(
                        "author_session_id",
                        "/answer/author_session_id",
                        AuditValue::Nullable,
                    ),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::FencedReplay,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            ),
            "Atomically answer and resolve one exact open todo. expected_assignment_fence is required and must be the exact opaque fence from get_session_assignment; completion_key separately keeps uncertain-result retries idempotent.",
            complete_session_message_input_schema,
        ),
        PERMISSION_RISK_WRITE,
    )),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "session_discussion_summary",
                ToolAuditPolicy {
                    request: AuditRequestPolicy {
                        fields: &[
                            AuditField::new("project", "project", AuditValue::Copy),
                            AuditField::new("session_id", "session_id", AuditValue::Copy),
                            AuditField::new("limit", "limit", AuditValue::Copy),
                        ],
                        transform: AuditTransform::Fields,
                        typed: AuditTypedPolicy::Overrides { fields: &[], omit: &["project"] },
                    },
                    result: AuditResultPolicy::Fields(&[
                        AuditField::new("success", "success", AuditValue::Nullable),
                        AuditField::new("session_id", "session_id", AuditValue::Nullable),
                        AuditField::new("counts", "counts", AuditValue::Nullable),
                        AuditField::new("open_todo_count", "open_todos", AuditValue::NullableCount),
                        AuditField::new(
                            "recent_answer_count",
                            "recent_answers",
                            AuditValue::NullableCount,
                        ),
                        AuditField::new(
                            "recent_completion_count",
                            "recent_completions",
                            AuditValue::NullableCount,
                        ),
                    ]),
                },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Return a bounded structured aggregate of session-local discussion from the recorded session ledger. Does not call an LLM or generate natural-language summaries.",
            session_discussion_summary_input_schema,
        )),
        15,
    ),
    requires_explicit_business_session(model_spec(
        def(
            "session_handoff_summary",
            ToolAuditPolicy {
                request: AuditRequestPolicy {
                    fields: &[
                        AuditField::new("project", "project", AuditValue::Copy),
                        AuditField::new("session_id", "session_id", AuditValue::Copy),
                        AuditField::new("include_workspace", "include_workspace", AuditValue::Copy),
                        AuditField::new(
                            "include_checkpoints",
                            "include_checkpoints",
                            AuditValue::Copy,
                        ),
                        AuditField::new("include_validation", "include_validation", AuditValue::Copy),
                        AuditField::new("summary_only", "summary_only", AuditValue::Copy),
                        AuditField::new("limit", "limit", AuditValue::Copy),
                    ],
                    transform: AuditTransform::Fields,
                    typed: AuditTypedPolicy::Same,
                },
                result: AuditResultPolicy::Fields(&[
                    AuditField::new("session_id", "session_id", AuditValue::Nullable),
                    AuditField::new("project", "project", AuditValue::Nullable),
                    AuditField::new("lifecycle", "lifecycle", AuditValue::Nullable),
                    AuditField::new("counts", "counts", AuditValue::Nullable),
                    AuditField::new("open_todo_count", "open_todos", AuditValue::NullableCount),
                    AuditField::new(
                        "recent_answer_count",
                        "recent_answers",
                        AuditValue::NullableCount,
                    ),
                    AuditField::new(
                        "recent_completion_count",
                        "recent_completions",
                        AuditValue::NullableCount,
                    ),
                    AuditField::new("summary_only", "summary_only", AuditValue::Nullable),
                    AuditField::new("error_kind", "error_kind", AuditValue::Nullable),
                ]),
            },
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Read-only handoff for multi-step tasks, explicit session_id. Reads session ledger collaboration and ledger-derived validation. Diagnostics use bounded tails or safe result metadata; validation.parser.available is false if absent. Worker/coordinator read.",
        session_handoff_summary_input_schema,
    )),
];
