use super::RunnerCapabilityRequirement::{FileRead, SkillStoreManage};
use super::ToolVisibility::ModelHidden;
use super::{def, ToolDefinition, TOOL_CATEGORY_RUNTIME};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{Read, SkillManage},
    ADMIN, PROJECT_READ, TOOL_PROVIDER_RUNNER,
};

/// Fixed Phase-3 project Skill runtime tools. They are known to the kernel but
/// intentionally hidden from the generic registry; Stateless MCP 2026 Full
/// Operator projects them explicitly, and the kernel capability gate remains
/// authoritative for execution.
pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    def(
        "skill_list",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "skill_read_file",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("source_scope"),
            super::ToolAuditResultField::value("trust"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "skill_versions",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillStoreManage),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "skill_install",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("artifact_sha256"),
            super::ToolAuditResultField::value("file_count"),
            super::ToolAuditResultField::value("total_bytes"),
            super::ToolAuditResultField::value("installed"),
            super::ToolAuditResultField::value("activated"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillStoreManage),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "skill_activate",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("previous_active_package_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("changed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillStoreManage),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "skill_remove_revision",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("removed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillStoreManage),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        true,
        false,
    ),
];
